name: Bump version and release
on:
  push:
    branches: [main]
jobs:
  bump_and_release:
    name: Bump and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Bump and Tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
      
      - name: get commit message
        id: commit_message
        run: |
          commit_message=$(git log -1 --pretty=%B | tr -d '\r' | tr '\n' ' ')
          echo "message=$commit_message" >> $GITHUB_OUTPUT
      
      - name: Github Release
        uses: ncipollo/release-action@v1.16.0
        with:
          tag: ${{steps.tag_version.outputs.new_tag}}
          name: Release $ {{ steps.tag_version.outputs.new_tag }}
          body: |
            ${{ steps.commit_message.outputs.message }}
            ${{ steps.tag_version.outputs.changelog }}